In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt 
from sklearn.cluster import KMeans 
from sklearn.metrics import silhouette_score
import seaborn as sns 

In [2]:
milk = pd.read_csv("milk.csv",index_col=0)
milk.head()

water  protein  fat  lactose   ash
Animal                                       
HORSE       90.1      2.6  1.0      6.9  0.35
ORANGUTAN   88.5      1.4  3.5      6.0  0.24
MONKEY      88.4      2.2  2.7      6.4  0.18
DONKEY      90.3      1.7  1.4      6.2  0.40
HIPPO       90.4      0.6  4.5      4.4  0.10

In [4]:
scaler = StandardScaler().set_output(transform='pandas')
scaler.fit(milk)
milk_scaled=scaler.transform(milk)

In [15]:
silhoutees_coefficient = []
ks = [2,3,4,5,6,7,8,9,10]
for k in ks:
    kmeans = KMeans(n_clusters=k, random_state=24)
    kmeans.fit(milk_scaled)
    silhoutees_coefficient.append(silhouette_score(milk_scaled, kmeans.labels_))

print(silhoutees_coefficient)
print(kmeans.cluster_centers_)
print(kmeans.labels_)

[np.float64(0.5258508931703421), np.float64(0.48757649189546187), np.float64(0.44348050284244644), np.float64(0.39423075374986555), np.float64(0.39485258676786045), np.float64(0.3720658628104658), np.float64(0.37602644048157396), np.float64(0.3768920557734793), np.float64(0.40757264882822525)]
[[-2.5905055   1.10038402  2.73077733 -2.0514601  -0.35016436]
 [ 0.68803584 -0.67397823 -0.68245174  0.67861988 -0.17326262]
 [-1.03649946  1.26338318  0.9792838  -1.05785956  1.28744032]
 [ 0.31180978  0.55550113 -0.39862246 -0.29640868  0.07439982]
 [ 0.89784656 -1.1825356  -0.79840935  1.15220518 -1.08203213]
 [-0.54813548  1.70115234  0.27092354 -1.24357929  2.90482766]
 [-0.59591022 -0.72986365  0.70758398  0.81790968 -0.47146841]
 [ 0.29588487 -0.04992431 -0.34687011  0.35361036  0.02048691]
 [ 0.97269365 -1.56814503 -0.56358307  0.14931866 -1.54298752]
 [-0.30129934  0.84889961  0.07200045 -0.54713031  0.88309349]]
[4 4 4 4 8 1 1 7 3 3 7 1 4 3 1 7 9 6 5 9 2 2 2 0 0]


In [17]:
k_max = np.argmax(silhoutees_coefficient)
print(f"Best Score : {silhoutees_coefficient[k_max]}")
print(f'Best value of K : {ks[k_max]}')

Best Score : 0.5258508931703421
Best value of K : 2


In [19]:
kmeans = KMeans(n_clusters=2,init="k-means++" ,random_state=24)
kmeans.fit(milk_scaled)

KMeans(n_clusters=2, random_state=24)

In [20]:
kmeans_data = milk.copy()
kmeans_data['Clust'] = kmeans.labels_
print( kmeans_data.groupby('Clust').mean() )

           water    protein        fat   lactose       ash
Clust                                                     
0      63.362500  10.412500  21.662500  1.975000  1.347500
1      85.158824   4.235294   4.964706  5.147059  0.635294
